### PR TITLE
Experimental 1.18 & 1.19 Support

### PR DESCRIPTION
**Pull request by Th3UnknownCoder**
1.18.2 changed the way Tags are done for Items and blocks, this adds experimental 1.18.2 support. I tested this on a personal server and it seems to work as expected, you may want to look it over and just double check before confirming.

### CODE REVIEW

**Comment by Th3UnknownCoder** [comment]
Its pretty simple, Open a Command Prompt, navigate to the project folder with cd, then run gradlew build. For those that don't wanna wait, there's a published build on my Github fork now.

**Comment by Th3UnknownCoder** [comment]
Will push an update if necessary for 1.19+, but not sure it'll need it yet.

**Comment by Th3UnknownCoder** [comment]
> @Th3UnknownCoder You wouldn't happen to know anything about baking models, would you?

Do you have Discord? I can add you to discuss it if you'd like?

**Comment by Th3UnknownCoder** [comment]
Added Support for 1.19, You may want to check it, as it probably breaks lower versions right now. Test Lib can be found
[simple_shelves-1.0.6.zip](https://github.com/Pinaz993/SimpleShelves/files/8865620/simple_shelves-1.0.6.zip)

**Comment by Pinaz993** [comment]
> > @Th3UnknownCoder You wouldn't happen to know anything about baking models, would you?
> 
> Do you have Discord? I can add you to discuss it if you'd like?

Pinaz993#4671

**Comment by Pinaz993** [comment]
I would like to apologize to all who were waiting on this merge. I plan to do some testing and merge this tomorrow, or Monday at the latest, after which, I will release new versions on CurseForge.

I have been working on a large refactor of the models that moves away from the Vanilla system of JSON defined models, and I didn't want to update until this was done. However, after a bout of clarity (you can read about it in issue #3) I realized that I had lost sight of what was really important. 

Once I release a 1.18/1.19 version (or versions, if need be), I will return to the baking problem, and hopefully solve the startup freezing issues that have been reported in the CurseForge comment section.

**Pull request merged**
